### ISSUE TITLE
讨论版有bug

### ISSUE THREAD

**Issue by AkutaZehy** [WZQ02/sometroublemakers-playground#1]
在选中一个表情后，按这个表情button，再按会失灵，发现了这样的bug。

![image](https://github.com/WZQ02/sometroublemaker.TV/assets/42381419/7a42baf9-3463-4c9d-9f9f-eb3d7654a6f4)

按下一次之后，表情可以正常打上去。

![image](https://github.com/WZQ02/sometroublemaker.TV/assets/42381419/21d74732-a1b5-42ce-b9f8-c4cdc1bf7b67)

再按同一个表情就没反应了。

![image](https://github.com/WZQ02/sometroublemaker.TV/assets/42381419/257089a6-9445-4536-a9ea-9ec8758bc255)

换一个表情又能正常打上去。

这个bug可以稳定复现（）

**Comment by WZQ02** [comment]
其实之前就已经发现这个问题了，只是一直懒得修。前两天想办法改了下表情选择区的逻辑，现在应该没这个问题了。
说到底这东西本来也就是个练手项目，也没打算做得多完善。
